import { StyleSheet } from "react-native";
import colors from "../constants/colors";

const PrimaryBorderRadius = 12;
const SecondaryBorderRadius = 100;

const styles = StyleSheet.create({
  Container: {
    flex: 1,
    backgroundColor: colors.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryContainer: {
    flex: 1,
    backgroundColor: colors.secondary,
    marginBottom: 10,
    marginTop: 60,
    margin: 12,
  },
  secondaryContainer: {
    flex: 1,
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: colors.secondary,
    justifyContent: "center",
  },
  image: {
    height: 150,
    width: 150,
    backgroundColor: colors.secondary,
    alignSelf: "center",
    justifyContent: "center",
  },
  secondImg: {
    height: 150,
    width: 150,
    marginBottom: -30,
    backgroundColor: colors.secondary,
    marginTop: 10,
    alignSelf: "center",
    justifyContent: "center",
  },
  mainTitle: {
    margin: 10,
    padding: 10,
    fontSize: 25,
    width: 238,
    textAlign: "center",
    alignSelf: "center",
    fontWeight: "bold",
    color: colors.primary,
    fontFamily: "Poppins-ExtraBold",
  },
  subTitle: {
    height: 75,
    width: 250,
    margin: 10,
    padding: -10,
    marginTop: 10,
    marginBottom: 10,
    alignSelf: "center",
    textAlign: "center",
    fontSize: 14,
    color: colors.primary,
    fontFamily: "Poppins-Medium",
  },
  Elearning: {
    fontSize: 21,
    textAlign: "center",
    fontWeight: "bold",
    color: colors.accent,
    fontFamily: "Poppins-Regular",
    marginTop: 17,
    marginBottom: 20,
  },
  primaryButton: {
    backgroundColor: colors.primaryLight,
    width: 270,
    height: 55,
    borderRadius: PrimaryBorderRadius,
    alignSelf: "center",
    marginTop: 21,
    marginBottom: 15,
  },
  buttonText: {
    fontSize: 15,
    height: 21,
    fontSize: 17,
    fontWeight: "bold",
    color: colors.secondary,
    alignSelf: "center",
    justifyContent: "center",
    marginTop: 18,
    fontFamily: "Poppins-Medium",
  },
  buttonContainer: {
    marginTop: 35,
    flexDirection: "row",
    borderColor: colors.primaryLight,
    borderWidth: 1,
    width: "75%",
    alignSelf: "center",
    height: 60,
    fontFamily: "Poppins-Medium",
    borderRadius: SecondaryBorderRadius,
  },
  secondaryButton: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    width: "50%",
    borderRadius: SecondaryBorderRadius,
  },
  loginButtonText: {
    color: colors.secondary,
    fontSize: 18,
    fontFamily: "Poppins-Medium",
  },
  signUpButtonText: {
    fontSize: 18,
    fontFamily: "Poppins-Medium",
    color: colors.primaryLight,
  },
  transparentButton: {
    backgroundColor: colors.secondary,
    width: 250,
    height: 40,
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 10,
  },
  transparentButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.primaryLight,
    fontFamily: "Poppins-Medium",
    marginTop: 10,
  },
  btnContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    marginBottom: 20,
  },
  createBtn: {
    borderColor: colors.facebook,
    borderWidth: 1,
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  createText: {
    color: colors.facebook,
    fontSize: 16,
  },
  joinBtn: {
    backgroundColor: colors.facebook,
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  joinText: {
    color: colors.secondary,
    fontSize: 16,
  },
  inputContainer: {
    marginTop: 10,
    width: 330,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 8,
    margin: 10,
  },
  input: {
    borderWidth: 1,
    width: 325,
    height: 58,
    alignSelf: "center",
    flexDirection: "row",
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: PrimaryBorderRadius,
    paddingHorizontal: 10,
  },
  signUpLink: {
    color: colors.primaryLight,
    marginTop: 4,
    fontWeight: "500",
    textDecorationLine: "underline",
    fontSize: 14,
    height: 17,
    width: 138,
    marginLeft: 18,
  },
  signUpText: {
    color: colors.Primary,
    marginLeft: 62,
    marginTop: 5,
  },
  resendContainer: {
    flexDirection: "row",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginLeft: -10,
    marginRight: -34,
    marginTop: 6,
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: -75,
  },
  rememberText: {
    marginLeft: 8,
    color: colors.placeholder,
  },
  boxContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    width: "80%",
    alignSelf: "center",
  },
  iconBox: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: PrimaryBorderRadius,
    padding: 10,
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    marginTop: 10,
  },
  sideTitle: {
    marginLeft: -75,
    marginBottom: 35,
    margin: 10,
    padding: 22,
    fontSize: 30,
    color: colors.primary,
    fontWeight: 800,
    fontFamily: "Poppins-ExtraBold",
  },
  sideDescription: {
    width: 250,
    height: 60,
    marginLeft: -60,
    marginTop: -40,
    fontSize: 14,
    color: colors.primary,
    fontFamily: "Poppins-Regular",
    fontWeight: "regular",
  },
  subjectDescription: {
    marginTop: -20,
    fontSize: 12,
    fontFamily: "Poppins-Medium",
    textAlign: "center",
  },
  phomeNumberContainer: {
    flexDirection: "row",
    marginBottom: 40,
  },
  phoneNumber: {
    fontSize: 14,
    fontWeight: 500,
    color: colors.primaryLight,
    marginRight: 160,
  },

  otpContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginVertical: 10,
    marginTop: 30,
    marginBottom: 80,
    marginLeft: -17,
    gap: 16,
  },
  inputBox: {
    width: 60,
    height: 60,
    borderRadius: 15,
    fontSize: 24,
    textAlign: "center",
    color: colors.text,
  },
  inputDefault: {
    backgroundColor: colors.background,
  },
  inputFilled: {
    backgroundColor: colors.info,
  },
  inputActive: {
    backgroundColor: colors.active,
    borderWidth: 2,
    borderColor: colors.info,
  },
  addButton: {
    position: "absolute",
    right: 1,
    top: 550,
    marginBottom: -70,
    backgroundColor: colors.secondary,
    borderRadius: 28,
    width: 56,
    height: 56,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
    borderBottomWidth: -1,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 99,
  },
  navbarIcon: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 30,
    padding: 10,
    marginHorizontal: -17,
  },
  navbarIconText: {
    fontSize: 20,
    marginBottom: 30,
    marginTop: 30,
    // marginBottom: -30,
    fontWeight: "500",
    flex: 1,
    textAlign: "center",
    marginLeft: 10,
    color: colors.accent,
    flexDirection: "row",
  },
  helpText: {
    textAlign: "center",
    color: "gray",
    fontSize: 16,
    fontStyle: "Poppins-Medium",
    marginTop: 45,
    marginBottom: 10,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "500",
  },
  disabledText: {
    fontSize: 16,
    color: colors.gray600,
    marginLeft: 20,
    padding: 7,
  },
  textInput: {
    borderWidth: 1,
    width: 320,
    height: 60,
    alignSelf: "center",
    flexDirection: "row",
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: PrimaryBorderRadius,
    paddingHorizontal: 10,
    marginBottom: 5,
    marginTop: 5,
  },
  link: {
    height: 17,
    width: 138,
    // marginRight: 18,
    color: colors.facebook,
    marginTop: 4,
    fontStyle: "Poppins-Regular",
    alignSelf: "center",
    fontWeight: "500",
    textDecorationLine: "underline",
    fontSize: 14,
  },
  helpLink: {
    color: colors.facebook,
    textDecorationLine: "underline",
    marginLeft: 35,
  },
  dividerContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    alignSelf: "center",
    marginVertical: 20,
  },
  dividerLine: {
    flex: 1,
    width: 300,
    height: 1,
    alignSelf: "center",
    backgroundColor: colors.gray300,
  },
  dividerText: {
    paddingHorizontal: 10,
    color: colors.textMuted,
  },
  container: {},
  announcementBox: {
    flexDirection: "row",
    alignSelf: "center",
    margin: 15,
    padding: 12,
    borderColor: colors.gray300,
    borderWidth: 1,
    width: 320,
    height: 57,
    marginLeft: 17,
    borderRadius: 10,
    backgroundColor: colors.background,
  },
  announcementText: {
    fontSize: 14,
    color: colors.textLight,
    alignSelf: "center",
    padding: 5,
  },
  bullet: {
    fontSize: 14,
    padding: 4,
    marginLeft: 20,
    marginBottom: 3,
    color: colors.textLight,
  },
  header: {
    height: 140,
    width: 350,
    // marginTop: -20,
    backgroundColor: colors.primaryLight,
    paddingVertical: 20,
    paddingHorizontal: 16,
    justifyContent: "flex-end",
    alignSelf: "center",
    alignItems: "flex-start",
    justifyContent: "center",
    borderBottomLeftRadius: 60,
    borderBottomRightRadius: 60,
    position: "relative",
  },
  classText: {
    fontWeight: "500",
    fontSize: 28,
    marginBottom: 60,
    marginLeft: 21,
    color: colors.secondary,
  },
  descriptionText: {
    fontWeight: "500",
    fontSize: 18,
    marginTop: -59,
    marginBottom: 43,
    marginLeft: 21,
    color: colors.secondary,
  },
  tabContainer: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: colors.gray300,
    alignItems: "center",
    backgroundColor: colors.secondary,
    justifyContent: "space-around",
    paddingVertical: 20,
    marginTop: 20,
  },
  tabItem: {
    alignItems: "center",
    flexDirection: "row",
  },
  label: {
    fontSize: 12,
    marginTop: 4,
    flexDirection: "row",
    margin: 5,
  },
  navContainer: {
    height: 70,
    width: 360,
    backgroundColor: colors.secondary,
    elevation: 4,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    justifyContent: "space-between",
    marginBottom: 50,
  },
  title: {
    fontSize: 18,
    marginTop: 25,
    color: colors.accent,
    fontWeight: "500",
    textAlign: "center",
    marginRight: 28,
  },
  userbtnContainer: {
    width: 330,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: colors.surfaceLight,
    borderRadius: 8,
    paddingHorizontal: 10,
    margin: 10,
  },
  textInputBtn: {
    flex: 1,
    height: 50,
    color: colors.accent,
  },
  button: {
    padding: 8,
  },

  card: {
    height: 100,
    width: 340,
    alignSelf: "center",
    borderRadius: 16,
    padding: 14,
    margin: 3,
    elevation: 4,
  },
  cardContent: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  cardTitle: {
    color: colors.secondary,
    fontSize: 18,
    fontWeight: "bold",
  },
  descriptionTitle: {
    color: colors.description,
    fontSize: 14,
    marginTop: 4,
  },
  students: {
    color: colors.secondary,
    fontSize: 13,
    marginTop: 10,
  },
  responciveContainer: {
    flexDirection: "row",
  },
  announcementBottonText: {
    color: "black",
    alignSelf: "center",
    justifyContent: "center",
    marginLeft: 10,
    fontSize: 14,
    fontStyle: "Poppins-Regular",
  },
  announcementBotton: {
    height: 50,
    width: "58%",
    marginLeft: -1,
    flexDirection: "row",
    backgroundColor: colors.secondary,
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 10,
    margin: 14,
  },
  repostBotton: {
    height: 50,
    width: "38%",
    marginLeft: -7,
    flexDirection: "row",
    backgroundColor: colors.secondary,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 10,
    margin: 14,
  },
  repostBottonText: {
    color: "black",
    alignSelf: "center",
    justifyContent: "center",
    marginLeft: 10,
    fontSize: 14,
    fontStyle: "Poppins-Regular",
  },
  lecCard: {
    height: 130,
    width: 340,
    backgroundColor: colors.gray600,
    alignSelf: "center",
    borderRadius: 16,
    padding: 10,
    margin: 10,
  },
  topSection: {},
  lecCardTitle: {
    color: colors.secondary,
    fontSize: 14,
    fontWeight: "bold",
    marginTop: -25,
    marginLeft: 22,
  },
  lecCardDiscription: {
    color: colors.secondary,
    fontSize: 15,
    fontWeight: "bold",
    marginLeft: 20,
  },
  date: {
    color: colors.border,
    fontSize: 14,
    marginLeft: 20,
  },
  commentInput: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.surfaceVariant,
    paddingTop: 10,
    color: colors.border,
  },

  userprofileContainer: {
    alignItems: "center",
    marginBottom: 30,
  },
  name: {
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 10,
  },
  editProfileButton: {
    backgroundColor: colors.primaryLight,
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 10,
    marginTop: 10,
  },
  editProfileText: {
    color: colors.secondary,
    fontWeight: "600",
  },
  changePasswordBtn: {
    width: 300,
    backgroundColor: colors.text,
    alignSelf: "center",
    marginTop: 30,
    paddingVertical: 12,
    borderRadius: 30,
    alignItems: "center",
  },
  changePasswordText: {
    color: colors.secondary,
    fontWeight: "bold",
  },
  logoutBtn: {
    width: 300,
    alignSelf: "center",
    borderColor: "red",
    borderWidth: 2,
    marginTop: 15,
    paddingVertical: 12,
    borderRadius: 30,
    alignItems: "center",
  },
  logoutText: {
    color: "red",
    fontWeight: "bold",
  },
  listContainer: {
    width: 350,
    padding: 10,
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: colors.gray200,
  },
  profileList: {
    flexDirection: "row",
    padding: 10,
    paddingVertical: 12,
    borderBottomWidth: 2,
    borderBottomColor: colors.gray200,
  },
  profileIconText: {
    fontSize: 14,
    fontWeight: "bold",
    marginLeft: 11,
    alignSelf: "center",
  },
  profileLabel: {
    marginLeft: 10,
    fontWeight: "bold",
    marginBottom: 5,
    marginTop: 15,
    fontSize: 16,
  },
  profileInput: {
    width: 320,
    paddingVertical: 15,
    alignSelf: "center",
    backgroundColor: colors.surfaceLight,
    borderRadius: 10,
    padding: 12,
    fontSize: 15,
  },
  passwordContainer: {
    width: 320,
    paddingVertical: 5,
    flexDirection: "row",
    backgroundColor: colors.surfaceLight,
    borderRadius: 10,
    alignItems: "center",
    alignSelf: "center",
    paddingHorizontal: 12,
    justifyContent: "space-between",
  },
  passwordInput: {
    flex: 1,
    fontSize: 15,
    paddingVertical: 12,
  },
  phoneContainer: {
    width: 320,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: colors.surfaceLight,
    borderRadius: 10,
    paddingVertical: 7,
  },
  phoneInput: {
    flex: 1,
    fontSize: 15,
  },
  postBtn: {
    height: 35,
    width: 80,
    marginTop: 30,
    marginLeft: 130,
    borderRadius: 100,
    backgroundColor: colors.primaryLight,
  },
  postBtnText: {
    fontSize: 14,
    marginTop: "7",
    color: colors.secondary,
    alignSelf: "center",
    fontWeight: "bold",
  },
  chipsRow: {
    flexDirection: "row",
    gap: 12,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.google,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
  },
  chipText: {
    color: "white",
    marginLeft: 6,
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    marginLeft: 8,
  },
  optionText: {
    color: colors.textMuted,
    marginLeft: 10,
    fontSize: 16,
  },

  attachmentCard: {
    width: 170,
    height: 100,
    padding: 8,
    backgroundColor: colors.surfaceDark,
    borderRadius: 12,
    padding: 8,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  caption: {
    flexDirection: "row",
    color: "black",
    marginLeft: -180,
    marginTop: 150,
    fontStyle: "Poppins-Regular",
  },
  attachmentContainer: {
    flexDirection: "row",
    gap: 6,
    marginLeft: -7,
  },
  bottomSheetcontainer: {
    flex: 1,
    backgroundColor: "grey",
    marginBottom: 50,
  },
  bottomsheetList: {
    flexDirection: "row",
    padding: 10,
    paddingVertical: 16,
    borderBottomColor: colors.gray200,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    height: 250,
    width: 330,
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: colors.text,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.gray200,
  },
  descriptionInput: {
    borderWidth: 2,
    width: 315,
    height: 58,
    borderColor: colors.facebook,
    borderRadius: 10,
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 20,
    padding: 12,
    fontSize: 15,
  },
  disabledButton: {
    opacity: 0.5,
  },
  caption: {
    alignSelf: "center",
    fontWeight: "500",
    fontSize: 14,
    paddingTop: 10,
    color: colors.gray700,
  },
  profileName: {
    alignSelf: "center",
    fontWeight: "500",
    fontSize: 18,
    paddingTop: 10,
    color: colors.facebook,
  },
  userInfosection: {
    alignItems: "center",
    marginBottom: 20,
    padding: 10,
    backgroundColor: colors.surfaceLight,
    borderRadius: 10,
    width: "90%",
    alignSelf: "center",
  },
  joinButton: {
    height: 45,
    width: 70,
    marginRight: 15,
    padding: 5,
    backgroundColor: colors.primaryLight,
    borderRadius: 50,
  },
  joinButtonText: {
    color: colors.secondary,
    // fontSize: 16,
    fontWeight: "bold",
    alignSelf: "center",
    marginTop: 7,
  },
  classCodeInput: {
    borderWidth: 2,
    width: 315,
    height: 58,
    borderRadius: 10,
    marginLeft: 19,
    marginTop: 10,
    padding: 12,
  },
  error: {
    color: "red",
    marginLeft: 20,
    fontSize: 12,
    marginTop: 8,
  },
});
export default styles;
