import { StyleSheet } from "react-native";

const PrimaryColor = "#2A2575";
const SecondaryColor = "'rgb(147, 147, 215)'";
const PrimaryBorderRadius = 12;
const SecondaryBorderRadius = 100;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    margin: 10,
    marginTop: 60,
    padding: 10,
    marginBottom: 80,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryContainer: {
    backgroundColor: "#fff",
    marginBottom: 200,
    marginTop: 80,
    margin: 12,
    // padding: 20,
  },
  secondaryContainer: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    marginTop: 220,
    marginBottom: 170,
    margin: 12,
    padding: 10,
  },
  image: {
    height: 200,
    width: 200,
    marginBottom: -20,
    marginHorizontal: 20,
    alignSelf: "center",
    justifyContent: "center",
  },
  secondImg: {
    height: 190,
    width: 200,
    marginBottom: -40,
    marginHorizontal: 20,
    alignSelf: "center",
    justifyContent: "center",
  },
  mainTitle: {
    margin: 10,
    padding: 10,
    fontSize: 25,
    width: 238,
    textAlign: "center",
    alignSelf: "center",
    fontWeight: "bold",
    color: PrimaryColor,
    fontFamily: "Poppins-ExtraBold",
  },
  subTitle: {
    height: 75,
    width: 250,
    margin: 10,
    padding: -10,
    // marginVertical: 20,
    marginTop: 10,
    marginBottom: 10,
    alignSelf: "center",
    textAlign: "center",
    fontSize: 14,
    color: PrimaryColor,
    fontFamily: "Poppins-Medium",
  },
  Elearning: {
    fontSize: 21,
    textAlign: "center",
    fontWeight: "bold",
    color: "#dea019",
    fontFamily: "Poppins-Regular",
    marginTop: 20,
    marginBottom: 20,
  },
  primaryButton: {
    backgroundColor: SecondaryColor,
    width: 270,
    height: 55,
    borderRadius: PrimaryBorderRadius,
    alignSelf: "center",
    marginTop: 18,
    marginBottom: 10,
  },
  buttonText: {
    fontSize: 15,
    height: 21,
    fontSize: 17,
    fontWeight: "bold",
    color: "#FFFFFF",
    alignSelf: "center",
    justifyContent: "center",
    marginTop: 18,
    fontFamily: "Poppins-Medium",
  },
  buttonContainer: {
    marginTop: 35,
    flexDirection: "row",
    borderColor: SecondaryColor,
    borderWidth: 1,
    width: "75%",
    alignSelf: "center",
    height: 60,
    fontFamily: "Poppins-Medium",
    borderRadius: SecondaryBorderRadius,
  },
  secondaryButton: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: SecondaryColor,
    width: "50%",
    borderRadius: SecondaryBorderRadius,
  },
  loginButtonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontFamily: "Poppins-Medium",
  },
  signUpButtonText: {
    fontSize: 18,
    fontFamily: "Poppins-Medium",
    color: SecondaryColor,
  },
  transparentButton: {
    backgroundColor: "#fff",
    width: 250,
    height: 40,
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 10,
  },
  transparentButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: SecondaryColor,
    fontFamily: "Poppins-Medium",
    marginTop: 10,
  },
  btnContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    marginBottom: 20,
  },
  createBtn: {
    borderColor: "#1a73e8",
    borderWidth: 1,
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  createText: {
    color: "#1a73e8",
    fontSize: 16,
  },
  joinBtn: {
    backgroundColor: "#1a73e8",
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  joinText: {
    color: "#fff",
    fontSize: 16,
  },

  inputContainer: {
    marginTop: 20,
  },
  input: {
    borderWidth: 1,
    width: 325,
    height: 58,
    flexDirection: "row",
    borderColor: "#ccc",
    color: "#808080",
    borderWidth: 1,
    borderRadius: PrimaryBorderRadius,
    alignSelf: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    marginBottom: 5,
    marginTop: 5,
  },
  signUpLink: {
    color: SecondaryColor,
    marginTop: 4,
    fontWeight: "500",
    textDecorationLine: "underline",
    fontSize: 14,
    height: 17,
    width: 138,
    marginLeft: 18,
  },
  signUpText: {
    color: PrimaryColor,
    marginLeft: 62,
    marginTop: 5,
  },
  resendContainer: {
    flexDirection: "row",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginLeft: -10,
    marginRight: -34,
    marginTop: 6,
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 20,
  },
  rememberText: {
    marginLeft: 4,
    color: "#888",
  },
  //  forgotText: {
  //   color: '#3D5CFF',
  // },
  boxContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    width: "80%",
    alignSelf: "center",
  },
  iconBox: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: PrimaryColor,
    borderRadius: PrimaryBorderRadius,
    padding: 10,
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    marginTop: 10,
  },
  sideTitle: {
    marginLeft: -10,
    marginBottom: 35,
    margin: 10,
    padding: 22,
    fontSize: 30,
    color: PrimaryColor,
    fontWeight: 800,
    fontFamily: "Poppins-ExtraBold",
  },
  sideDescription: {
    width: 250,
    height: 60,
    marginLeft: 11,
    marginTop: -40,
    fontSize: 14,
    color: PrimaryColor,
    fontFamily: "Poppins-Regular",
    fontWeight: "regular",
  },
  subjectDescription: {
    marginTop: -20,
    fontSize: 12,
    fontFamily: "Poppins-Medium",
    textAlign: "center",
  },
  phomeNumberContainer: {
    flexDirection: "row",
    marginBottom: 40,
  },
  phoneNumber: {
    fontSize: 14,
    fontWeight: 500,
    color: "'rgb(147, 147, 215)'",
    marginRight: 160,
  },

  otpContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginVertical: 10,
    marginTop: 30,
    marginBottom: 80,
    marginLeft: -17,
    gap: 16,
  },
  inputBox: {
    width: 60,
    height: 60,
    borderRadius: 15,
    fontSize: 24,
    textAlign: "center",
    color: "#000",
  },
  inputDefault: {
    backgroundColor: "#f1f1f1",
  },
  inputFilled: {
    backgroundColor: "#4DB6FF",
  },
  inputActive: {
    backgroundColor: "#B3E5FC",
    borderWidth: 2,
    borderColor: "#4DB6FF",
  },
  addButton: {
    position: "absolute",
    right: 1,
    top: 600,
    marginBottom: -40,
    // bottom: -70,
    backgroundColor: "#fff",
    borderRadius: 28,
    width: 56,
    height: 56,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
    borderBottomWidth: -1,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 99,
  },
  navbarIcon: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 30,
    padding: 10,
    marginHorizontal: -17,
  },
  navbarIconText: {
    fontSize: 20,
    marginBottom: 30,
    marginTop: 30,
    // marginBottom: -30,
    fontWeight: "500",
    flex: 1,
    textAlign: "center",
    marginLeft: 10,
    color: "#dea019",
    flexDirection: "row",
  },
  helpText: {
    textAlign: "center",
    color: "gray",
    fontSize: 16,
    fontStyle: "Poppins-Medium",
    marginTop: 45,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "500",
  },
  disabledText: {
    fontSize: 16,
    color: "#808080",
    marginLeft: 20,
    padding: 7,
  },
  textInput: {
    borderWidth: 1,
    width: 320,
    height: 60,
    alignSelf: "center",
    flexDirection: "row",
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: PrimaryBorderRadius,
    paddingHorizontal: 10,
    marginBottom: 5,
    marginTop: 5,
  },
  link: {
    height: 17,
    width: 138,
    marginRight: 18,
    color: "rgb(28, 117, 234)",
    marginTop: 4,
    fontStyle: "Poppins-Regular",
    alignSelf: "center",
    fontWeight: "500",
    textDecorationLine: "underline",
    fontSize: 14,
  },
  helpLink: {
    color: "#1a73e8",
    textDecorationLine: "underline",
    marginLeft: 27,
  },
  dividerContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    alignSelf: "center",
    marginVertical: 20,
  },
  dividerLine: {
    flex: 1,
    width: 300,
    height: 1,
    alignSelf: "center",
    backgroundColor: "#ddd",
  },
  dividerText: {
    paddingHorizontal: 10,
    color: "#888",
  },
  container: {},
  announcementBox: {
    flexDirection: "row",
    alignSelf: "center",
    margin: 15,
    padding: 12,
    borderColor: "#ccc",
    borderWidth: 1,
    width: 320,
    height: 57,
    marginLeft: 17,
    borderRadius: 10,
    backgroundColor: "#f9f9f9",
  },
  announcementText: {
    fontSize: 14,
    color: "#555",
    alignSelf: "center",
    padding: 5,
  },
  bullet: {
    fontSize: 14,
    padding: 4,
    marginLeft: 20,
    marginBottom: 3,
    color: "#444",
  },
  header: {
    height: 150,
    width: 342,
    backgroundColor: SecondaryColor,
    justifyContent: "flex-end",
    alignSelf: "center",
    borderBottomLeftRadius: 60,
    borderBottomRightRadius: 60,
    position: "relative",
  },
  classText: {
    fontWeight: "500",
    fontSize: 28,
    marginBottom: 60,
    marginLeft: 21,
    color: "#fff",
  },
  descriptionText: {
    fontWeight: "500",
    fontSize: 18,
    marginTop: -59,
    marginBottom: 43,
    marginLeft: 21,
    color: "#fff",
  },
  tabContainer: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#ddd",
    backgroundColor: "#fff",
    justifyContent: "space-around",
    paddingVertical: 10,
    marginTop: 50,
  },
  tabItem: {
    alignItems: "center",
    flexDirection: "row",
  },
  label: {
    fontSize: 12,
    marginTop: 4,
    flexDirection: "row",
  },
  navContainer: {
    height: 56,
    width: 360,
    backgroundColor: "#fff",
    elevation: 4,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    justifyContent: "space-between",
    marginBottom: 50,
  },
  title: {
    fontSize: 18,
    color: "#dea019",
    fontWeight: "500",
    flex: 1,
    textAlign: "center",
    marginRight: 28,
  },
  userbtnContainer: {
    width: 330,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#f5f5f5",
    borderRadius: 8,
    paddingHorizontal: 10,
    margin: 10,
  },
  textInputBtn: {
    flex: 1,
    height: 50,
    color: "#dea019",
  },
  button: {
    padding: 8,
  },

  card: {
    height: 100,
    width: 340,
    alignSelf: "center",
    borderRadius: 16,
    padding: 14,
    margin: 3,
    elevation: 4,
  },
  cardContent: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  cardTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  descriptionTitle: {
    color: "#e0e0e0",
    fontSize: 14,
    marginTop: 4,
  },
  students: {
    color: "#fff",
    fontSize: 13,
    marginTop: 10,
  },
  responciveContainer: {
    flexDirection: "row",
  },
  announcementBottonText: {
    color: "black",
    alignSelf: "center",
    justifyContent: "center",
    marginLeft: 10,
    fontSize: 14,
    fontStyle: "Poppins-Regular",
  },
   announcementBotton: {
    height: 50,
    width: "58%",
    marginLeft: -1,
    flexDirection: "row",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 10,
    margin: 14,
  },
  repostBotton: {
    height: 50,
    width: "38%",
    marginLeft: -7,
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 10,
    margin: 14,
  },
  repostBottonText: {
    color: "black",
    alignSelf: "center",
    justifyContent: "center",
    marginLeft: 10,
    fontSize: 14,
    fontStyle: "Poppins-Regular",
  },
  lecCard: {
    height: 130,
    width: 340,
    backgroundColor: "#808080",
    alignSelf: "center",
    borderRadius: 16,
    padding: 10,
    margin: 10,
  },
  topSection: {},
  lecCardTitle: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
    marginTop: -25,
    marginLeft: 22,
  },
  lecCardDiscription: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "bold",
    marginLeft: 20,
  },
  date: {
    color: "#ccc",
    fontSize: 14,
    marginLeft: 20,
  },
  commentInput: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#333",
    paddingTop: 10,
    color: "#ccc",
  },

  userprofileContainer: {
    alignItems: "center",
    marginBottom: 30,
  },
  name: {
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 10,
  },
  editProfileButton: {
    backgroundColor: SecondaryColor,
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 10,
    marginTop: 10,
  },
  editProfileText: {
    color: "#fff",
    fontWeight: "600",
  },
  changePasswordBtn: {
    width: 300,
    backgroundColor: "#000",
    alignSelf: "center",
    marginTop: 30,
    paddingVertical: 12,
    borderRadius: 30,
    alignItems: "center",
  },
  changePasswordText: {
    color: "#fff",
    fontWeight: "bold",
  },
  logoutBtn: {
    width: 300,
    alignSelf: "center",
    borderColor: "red",
    borderWidth: 2,
    marginTop: 15,
    paddingVertical: 12,
    borderRadius: 30,
    alignItems: "center",
  },
  logoutText: {
    color: "red",
    fontWeight: "bold",
  },
  listContainer: {
    flexDirection: "row",
    position: "absolute",
    padding: 10,
  },
  profileList: {
    flexDirection: "row",
    padding: 10,
    paddingVertical: 16,
    borderBottomWidth: 2,
    borderBottomColor: "#eee",
  },
  profileIconText: {
    fontSize: 14,
    fontWeight: "bold",
    marginLeft: 11,
    alignSelf: "center",
  },
  profileLabel: {
    marginLeft: 10,
    fontWeight: "bold",
    marginBottom: 5,
    marginTop: 15,
    fontSize: 16,
  },
  profileInput: {
    width: 320,
    paddingVertical: 15,
    alignSelf: "center",
    backgroundColor: "#f5f5f5",
    borderRadius: 10,
    padding: 12,
    fontSize: 15,
  },
  passwordContainer: {
    width: 320,
    paddingVertical: 5,
    flexDirection: "row",
    backgroundColor: "#f5f5f5",
    borderRadius: 10,
    alignItems: "center",
    alignSelf: "center",
    paddingHorizontal: 12,
    justifyContent: "space-between",
  },
  passwordInput: {
    flex: 1,
    fontSize: 15,
    paddingVertical: 12,
  },
  phoneContainer: {
    width: 320,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#f5f5f5",
    borderRadius: 10,
    paddingVertical: 7,
  },
  phoneInput: {
    flex: 1,
    fontSize: 15,
  },
  postBtn: {
    height: 42,
    width: 80,
    marginLeft: 130,
    borderRadius: 100,
    backgroundColor: SecondaryColor,
  },
  postBtnText: {
    fontSize: 14,
    marginTop: "10",
    color: "#fff",
    alignSelf: "center",
    fontWeight: "bold",
  },
   chipsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#01579b',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
  },
  chipText: {
    color: 'white',
    marginLeft: 6,
  },
   optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    marginLeft: 8,
  },
  optionText: {
    color: '#888',
    marginLeft: 10,
    fontSize: 16,
  },









 attachmentCard: {
    width: 170,
    height: 100,
    padding: 8,
    backgroundColor: '#1e1e1e',
    borderRadius: 12,
    padding: 8,
    alignSelf: "center",
    justifyContent: 'center',
    alignItems: 'center',
  },
  caption: {
    flexDirection: "row",
    color: 'black',
    marginLeft: -180,
    marginTop: 150,
    fontStyle: "Poppins-Regular",
  },
  attachmentContainer:{
    flexDirection: "row",
    gap: 6,
    marginLeft: -7,
  }
});
export default styles;
